import 'dart:io';
import 'package:path/path.dart' as p;

import 'dart/model_generator.dart' show GeneratedFile;

/// Emits the transport runtime package (`purple_openapi_core`).
///
/// Spec-independent: the file bodies are the fixed runtime contract (see the
/// Phase 3 Kiota-lite BUILD SPEC §2). Regenerable — this generator is the single
/// source of truth for the fleet's shared transport, so client emits and the
/// runtime emit never drift.
///
/// Invoked via `--emit-target=runtime`; needs no OpenAPI spec.
class RuntimePackageGenerator {
  RuntimePackageGenerator({
    required this.outputDir,
    required this.packageName,
  });

  final String outputDir;
  final String packageName;

  Future<void> generate() async {
    final root = p.join(outputDir, packageName);
    for (final f in _files()) {
      final path = p.join(root, f.path);
      await Directory(p.dirname(path)).create(recursive: true);
      await File(path).writeAsString(f.content);
    }
    try {
      final result = await Process.run(
        'dart',
        ['format', '.'],
        workingDirectory: root,
      );
      if (result.exitCode != 0) {
        print('Warning: dart format exited with code ${result.exitCode}');
      }
    } catch (e) {
      print('Warning: Could not format runtime package: $e');
    }
    print('Generated ${_files().length} runtime files in $root');
  }

  List<GeneratedFile> _files() => [
        GeneratedFile(path: 'pubspec.yaml', content: _pubspec),
        GeneratedFile(path: 'lib/$packageName.dart', content: _barrel),
        GeneratedFile(
            path: 'lib/src/request_information.dart', content: _reqInfo),
        GeneratedFile(path: 'lib/src/request_adapter.dart', content: _adapter),
        GeneratedFile(
            path: 'lib/src/dio_request_adapter.dart', content: _dioAdapter),
        GeneratedFile(path: 'lib/src/auth.dart', content: _auth),
        GeneratedFile(
            path: 'lib/src/api_exception.dart', content: _apiException),
        GeneratedFile(
            path: 'lib/src/error_handler.dart', content: _errorHandler),
        GeneratedFile(
            path: 'lib/src/interceptors.dart', content: _interceptors),
        GeneratedFile(path: 'lib/src/pagination.dart', content: _pagination),
      ];

  // ---------------------------------------------------------------------------
  // File bodies — verbatim runtime contract (§2). Raw strings (r'''...''')
  // preserve `$` / `${}` literally so the emitted package reproduces the
  // foundation copy byte-for-byte after `dart format`.
  // ---------------------------------------------------------------------------

  String get _pubspec => '''name: $packageName
resolution: workspace
description: >-
  Shared transport runtime for openapi_flutter_gen pure-surface (Kiota-lite) clients:
  a transport-neutral RequestInformation + RequestAdapter (dio-backed DioRequestAdapter),
  an injected AuthenticationProvider / AccessTokenProvider auth seam (Bearer, empty-token
  safe), a typed ApiException, and ported error/retry/logging/pagination. Zero model
  imports; dio + meta only. Emitted by openapi_flutter_gen (--emit-target=runtime) so it
  stays regenerable and is the single source of truth for the fleet's transport.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.12.0

dependencies:
  dio: ^5.7.0
  meta: ^1.15.0

dev_dependencies:
  test: ^1.25.0
  lints: ^6.0.0
''';

  String get _barrel => '''// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by openapi_flutter_gen (--emit-target=runtime)
//
/// Shared transport runtime for pure-surface (Kiota-lite) openapi clients:
/// a transport-neutral [RequestInformation] + [RequestAdapter]
/// ([DioRequestAdapter]), an injected [AuthenticationProvider] /
/// [AccessTokenProvider] auth seam, a typed [ApiException], and the ported
/// error/retry/logging/pagination infra. Zero model imports.
library;

export 'src/request_information.dart';
export 'src/request_adapter.dart';
export 'src/dio_request_adapter.dart';
export 'src/auth.dart';
export 'src/api_exception.dart';
export 'src/error_handler.dart';
export 'src/interceptors.dart';
export 'src/pagination.dart';

// Re-export the dio types that generated MODEL files still reference for binary
// props (toFormData / Uint8List), so pure-mode clients need no direct dio dep.
export 'package:dio/dio.dart' show FormData, MultipartFile;
export 'dart:typed_data' show Uint8List;
''';

  String get _reqInfo => r'''// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by openapi_flutter_gen (--emit-target=runtime)
//
/// HTTP verbs. String value is what the transport puts on the wire.
enum HttpMethod {
  get('GET'),
  post('POST'),
  put('PUT'),
  patch('PATCH'),
  delete('DELETE'),
  head('HEAD'),
  options('OPTIONS');

  const HttpMethod(this.value);
  final String value;
}

/// A transport-neutral description of an outbound request.
///
/// Generated `*Api` methods build one of these and hand it to a [RequestAdapter].
/// It carries NO dio types and NO model types — the body is already-serialized
/// JSON (`Map`/`List`/primitive from `model.toJson()`), and path/query params are
/// raw values the adapter renders/encodes.
class RequestInformation {
  RequestInformation({
    required this.httpMethod,
    required this.urlTemplate,
    this.baseUrl,
    Map<String, Object?>? pathParameters,
    Map<String, Object?>? queryParameters,
    Map<String, String>? headers,
    this.body,
    this.contentType = 'application/json',
    Map<String, dynamic>? options,
  })  : pathParameters = pathParameters ?? <String, Object?>{},
        queryParameters = queryParameters ?? <String, Object?>{},
        headers = headers ?? <String, String>{},
        options = options ?? <String, dynamic>{};

  /// Verb.
  final HttpMethod httpMethod;

  /// Path template relative to [baseUrl] with `{name}` placeholders,
  /// e.g. `/{culture}/api/AddressManager/Autocomplete`. The emitter passes the
  /// RAW template + [pathParameters] so rendering/encoding lives in one place.
  final String urlTemplate;

  /// Optional per-request base URL override (else the adapter's baseUrl).
  final String? baseUrl;

  /// Values substituted into `{...}` placeholders in [urlTemplate].
  /// Non-string values are `toString()`'d; each segment is URL-encoded.
  final Map<String, Object?> pathParameters;

  /// Query string parameters. `null` values are dropped; `Iterable` values
  /// expand to repeated keys (`?id=1&id=2`).
  final Map<String, Object?> queryParameters;

  /// Per-request headers. Auth is NOT set here — the [AuthenticationProvider]
  /// applies it just before send.
  final Map<String, String> headers;

  /// Already-serialized request payload: `Map<String,dynamic>`, `List`,
  /// primitive, `Uint8List`, `FormData`, or `null`. Produced by callers via
  /// `model.toJson()` / `toFormData()`. The adapter does NOT know about models.
  Object? body;

  /// Abstract content type of [body]. Default JSON; overridable for
  /// multipart / octet-stream endpoints.
  String contentType;

  /// Opaque per-call metadata bag forwarded to the transport (dio `extra`).
  /// Carries e.g. `perCallErrorHandler`.
  final Map<String, dynamic> options;

  /// Merge a header without clobbering intent (used by auth providers).
  void addHeader(String name, String value) => headers[name] = value;

  /// Convenience content setters (used by the emitter).
  void setJsonContent(Object? json) {
    body = json;
    contentType = 'application/json';
  }

  void setStreamContent(Object? bytes) {
    body = bytes; // Uint8List
    contentType = 'application/octet-stream';
  }

  void setMultipartContent(Object? formData) {
    body = formData; // dio FormData (re-exported by this package)
    contentType = 'multipart/form-data';
  }

  /// Renders [urlTemplate] against [pathParameters] with per-segment encoding.
  /// Pure helper (no dio dependency) — used by the adapter to build the path.
  String renderPath() {
    return urlTemplate.replaceAllMapped(RegExp(r'\{(\w+)\}'), (m) {
      final key = m.group(1)!;
      final raw = pathParameters[key];
      return Uri.encodeComponent(raw?.toString() ?? '');
    });
  }
}
''';

  String get _adapter => r'''// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by openapi_flutter_gen (--emit-target=runtime)
//
import 'request_information.dart';

/// Deserializers injected by the caller. The adapter never imports models;
/// generated `*Api` methods pass `Model.fromJson`.
typedef ModelDeserializer<T> = T Function(Map<String, dynamic> json);
typedef PrimitiveDeserializer<T> = T Function(Object? value);

/// Transport-neutral executor. One instance is shared by all `*Api` classes
/// (injected, replacing the `Dio`/`baseUrl` they hold today).
abstract class RequestAdapter {
  /// Base URL prepended to each [RequestInformation.urlTemplate].
  String get baseUrl;

  /// Sends and deserializes a single JSON object body via [deserialize].
  /// Throws `ApiException` on non-2xx.
  Future<T> send<T>(RequestInformation request, ModelDeserializer<T> deserialize);

  /// Sends and deserializes a JSON array, mapping each element with [deserialize].
  Future<List<T>> sendList<T>(
      RequestInformation request, ModelDeserializer<T> deserialize);

  /// Sends and returns a primitive/scalar (`bool`, `int`, `String`, raw
  /// `Uint8List` for octet-stream, etc.). [convert] defaults to an identity cast.
  Future<T> sendPrimitive<T>(RequestInformation request,
      {PrimitiveDeserializer<T>? convert});

  /// Sends a request expecting no body (204 / fire-and-forget).
  Future<void> sendNoContent(RequestInformation request);
}
''';

  String get _dioAdapter => r'''// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by openapi_flutter_gen (--emit-target=runtime)
//
import 'dart:typed_data';

import 'package:dio/dio.dart';

import 'api_exception.dart';
import 'auth.dart';
import 'error_handler.dart';
import 'interceptors.dart';
import 'request_adapter.dart';
import 'request_information.dart';

/// The ONLY dio-touching class. Owns one [Dio], applies the injected
/// [AuthenticationProvider] per request, wires the error/retry/logging
/// interceptors, and maps non-2xx to a typed [ApiException].
class DioRequestAdapter implements RequestAdapter {
  DioRequestAdapter({
    required this.baseUrl,
    AuthenticationProvider? authenticationProvider,
    Dio? dio,
    ApiErrorInterceptor? errorHandler,
    RetryInterceptor? retryInterceptor,
    LoggingInterceptor? loggingInterceptor,
    List<Interceptor> interceptors = const [],
  })  : _auth = authenticationProvider ?? const AnonymousAuthenticationProvider(),
        _dio = dio ?? Dio(),
        _retryableStatuses =
            (retryInterceptor ?? RetryInterceptor()).retryableStatuses {
    _dio.options.baseUrl = baseUrl;
    // Order: error callbacks first (see response), then retry, then log.
    if (errorHandler != null) _dio.interceptors.add(errorHandler);
    final retry = retryInterceptor ?? RetryInterceptor();
    retry.dio = _dio; // fix: retries reuse THIS configured dio
    _dio.interceptors.add(retry);
    if (loggingInterceptor != null) _dio.interceptors.add(loggingInterceptor);
    _dio.interceptors.addAll(interceptors);
  }

  @override
  final String baseUrl;
  final AuthenticationProvider _auth;
  final Dio _dio;
  final Set<int> _retryableStatuses;

  @override
  Future<T> send<T>(
      RequestInformation request, ModelDeserializer<T> deserialize) async {
    final response = await _execute(request, ResponseType.json);
    final data = response.data;
    if (data is Map<String, dynamic>) return deserialize(data);
    if (data is Map) return deserialize(Map<String, dynamic>.from(data));
    throw _mismatch(request, response, 'JSON object', data);
  }

  @override
  Future<List<T>> sendList<T>(
      RequestInformation request, ModelDeserializer<T> deserialize) async {
    final response = await _execute(request, ResponseType.json);
    final data = response.data;
    if (data is List) {
      return data
          .map((e) => deserialize(Map<String, dynamic>.from(e as Map)))
          .toList();
    }
    throw _mismatch(request, response, 'JSON array', data);
  }

  @override
  Future<T> sendPrimitive<T>(RequestInformation request,
      {PrimitiveDeserializer<T>? convert}) async {
    final wantsBytes = T == Uint8List;
    final response =
        await _execute(request, wantsBytes ? ResponseType.bytes : ResponseType.json);
    final data = response.data;
    if (convert != null) return convert(data);
    if (wantsBytes && data is List<int>) return Uint8List.fromList(data) as T;
    return data as T;
  }

  @override
  Future<void> sendNoContent(RequestInformation request) async {
    await _execute(request, ResponseType.json);
  }

  // ---- shared pipeline ----

  Future<Response<dynamic>> _execute(
      RequestInformation request, ResponseType responseType) async {
    await _auth.authenticateRequest(request); // may add Authorization, or nothing

    try {
      final response = await _dio.request<dynamic>(
        request.renderPath(),
        data: request.body,
        queryParameters: _normalizeQuery(request.queryParameters),
        options: Options(
          method: request.httpMethod.value,
          headers: {'Content-Type': request.contentType, ...request.headers},
          responseType: responseType,
          extra: request.options,
          // D-R2: let ONLY retryable statuses fall through to onError (retry),
          // while non-retryable non-2xx reach onResponse (error callbacks) and
          // are then mapped to ApiException by the explicit 2xx check below.
          validateStatus: (s) =>
              s != null && s < 500 && !_retryableStatuses.contains(s),
        ),
      );
      final status = response.statusCode ?? 0;
      if (status < 200 || status >= 300) {
        throw _toApiException(request, response, null);
      }
      return response;
    } on DioException catch (e) {
      if (e.response != null) throw _toApiException(request, e.response!, e);
      throw ApiException(
        statusCode: 0,
        method: request.httpMethod.value,
        uri: '$baseUrl${request.renderPath()}',
        message: e.message,
        cause: e,
      );
    }
  }

  ApiException _toApiException(
          RequestInformation req, Response<dynamic> res, Object? cause) =>
      ApiException(
        statusCode: res.statusCode ?? 0,
        method: req.httpMethod.value,
        uri: '$baseUrl${req.renderPath()}',
        responseBody: res.data,
        responseHeaders: res.headers.map,
        message: res.statusMessage,
        cause: cause,
      );

  ApiException _mismatch(
          RequestInformation req, Response<dynamic> res, String want, Object? got) =>
      ApiException(
        statusCode: res.statusCode ?? 0,
        method: req.httpMethod.value,
        uri: '$baseUrl${req.renderPath()}',
        responseBody: res.data,
        message: 'Expected $want but got ${got.runtimeType}',
      );

  Map<String, dynamic>? _normalizeQuery(Map<String, Object?> q) {
    if (q.isEmpty) return null;
    final out = <String, dynamic>{};
    q.forEach((k, v) {
      if (v != null) out[k] = v;
    }); // drop nulls; dio expands Iterables
    return out.isEmpty ? null : out;
  }
}
''';

  String get _auth => r'''// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by openapi_flutter_gen (--emit-target=runtime)
//
import 'request_information.dart';

/// Yields the raw bearer token (JWT) on demand. The seam the app implements to
/// bridge its token store (secure storage, memory, refresh flow) to the client.
abstract class AccessTokenProvider {
  /// Return the current token, or `null`/empty when unauthenticated.
  Future<String?> getAuthorizationToken();
}

/// Strategy that mutates a [RequestInformation] to carry credentials.
abstract class AuthenticationProvider {
  Future<void> authenticateRequest(RequestInformation request);
}

/// No-op provider (unauthenticated / catalog Bearer-optional calls).
class AnonymousAuthenticationProvider implements AuthenticationProvider {
  const AnonymousAuthenticationProvider();

  @override
  Future<void> authenticateRequest(RequestInformation request) async {}
}

/// Adds `Authorization: Bearer <token>` — ONLY when the token is present.
///
/// THE BUG FIX: the old `BearerSecurity`/`AuthInterceptor` set the header
/// whenever `token != null`, so an empty string `''` produced a bare
/// `Authorization: Bearer ` which the backend parsed as a malformed token
/// (IDX12709, first-login-impossible). Here null AND empty/whitespace are
/// treated as "no credentials" and NO header is emitted.
class BearerAuthenticationProvider implements AuthenticationProvider {
  const BearerAuthenticationProvider(
    this.tokenProvider, {
    this.headerName = 'Authorization',
    this.scheme = 'Bearer',
  });

  final AccessTokenProvider tokenProvider;
  final String headerName;
  final String scheme;

  @override
  Future<void> authenticateRequest(RequestInformation request) async {
    final token = await tokenProvider.getAuthorizationToken();
    if (token == null || token.trim().isEmpty) return; // <-- no bare "Bearer "
    request.addHeader(headerName, '$scheme $token');
  }
}

/// Convenience adapter over a plain (nullable) token string.
class StaticAccessTokenProvider implements AccessTokenProvider {
  const StaticAccessTokenProvider(this.token);
  final String? token;

  @override
  Future<String?> getAuthorizationToken() async => token;
}

/// Convenience adapter over a `Future<String?> Function()` (the old
/// `tokenProvider` callback shape), so migration is mechanical.
class CallbackAccessTokenProvider implements AccessTokenProvider {
  const CallbackAccessTokenProvider(this.callback);
  final Future<String?> Function() callback;

  @override
  Future<String?> getAuthorizationToken() => callback();
}
''';

  String get _apiException => r'''// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by openapi_flutter_gen (--emit-target=runtime)
//

/// Thrown by a `RequestAdapter` on any non-2xx (after the error-callback surface
/// has had its chance). Carries enough for callers to branch without a dio import.
class ApiException implements Exception {
  ApiException({
    required this.statusCode,
    required this.method,
    required this.uri,
    this.responseBody,
    this.responseHeaders = const {},
    this.message,
    this.cause,
  });

  final int statusCode;
  final String method;
  final String uri;

  /// Decoded body when available (`Map`/`List`/`String`), else raw string.
  final Object? responseBody;
  final Map<String, List<String>> responseHeaders;
  final String? message;

  /// Underlying transport error (e.g. the original `DioException`) for debugging.
  /// Typed as `Object?` to keep this class dio-free at the API surface.
  final Object? cause;

  bool get isUnauthorized => statusCode == 401;
  bool get isClientError => statusCode >= 400 && statusCode < 500;
  bool get isServerError => statusCode >= 500;

  @override
  String toString() =>
      'ApiException($statusCode $method $uri): ${message ?? responseBody}';
}
''';

  String get _errorHandler => r'''// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by openapi_flutter_gen (--emit-target=runtime)
//
import 'package:dio/dio.dart';

typedef StatusCodeCallback = void Function(Response<dynamic> response);
typedef AnyStatusCodeCallback = void Function(
    int statusCode, Response<dynamic> response);

/// Status-code → callback surface. Runs inside the `DioRequestAdapter` pipeline.
/// Because the adapter uses a permissive `validateStatus` for non-retryable
/// non-2xx, those arrive here as `onResponse` (not `onError`), same as before.
class ApiErrorInterceptor extends Interceptor {
  ApiErrorInterceptor({
    this.onBadRequest,
    this.onUnauthorized,
    this.onForbidden,
    this.onNotFound,
    this.onConflict,
    this.onTooManyRequests,
    this.onServerError,
    this.onAny,
    this.skipGlobal = false,
  });

  final StatusCodeCallback? onBadRequest;
  final StatusCodeCallback? onUnauthorized;
  final StatusCodeCallback? onForbidden;
  final StatusCodeCallback? onNotFound;
  final StatusCodeCallback? onConflict;
  final StatusCodeCallback? onTooManyRequests;
  final StatusCodeCallback? onServerError;
  final AnyStatusCodeCallback? onAny;
  final bool skipGlobal;

  @override
  void onResponse(Response<dynamic> response, ResponseInterceptorHandler handler) {
    final status = response.statusCode ?? 0;
    final perCall = response.requestOptions.extra['perCallErrorHandler'];
    if (perCall is ApiErrorInterceptor) {
      perCall._dispatch(status, response);
      if (perCall.skipGlobal) {
        handler.next(response);
        return;
      }
    }
    _dispatch(status, response);
    handler.next(response);
  }

  void _dispatch(int status, Response<dynamic> response) {
    onAny?.call(status, response);
    switch (status) {
      case 400:
        onBadRequest?.call(response);
      case 401:
        onUnauthorized?.call(response);
      case 403:
        onForbidden?.call(response);
      case 404:
        onNotFound?.call(response);
      case 409:
        onConflict?.call(response);
      case 429:
        onTooManyRequests?.call(response);
      default:
        if (status >= 500) onServerError?.call(response);
    }
  }
}
''';

  String get _interceptors => r'''// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by openapi_flutter_gen (--emit-target=runtime)
//
import 'package:dio/dio.dart';

/// The HTTP statuses that are worth retrying. Shared between [RetryInterceptor]
/// (which replays them) and the adapter's `validateStatus` (which lets ONLY
/// these reach `onError` so the retry path sees them) — see the build spec D-R2.
const Set<int> kRetryableStatuses = {408, 429, 500, 502, 503, 504};

class RetryInterceptor extends Interceptor {
  RetryInterceptor({
    this.maxRetries = 3,
    this.retryDelay = const Duration(seconds: 1),
    this.retryableStatuses = kRetryableStatuses,
  });

  final int maxRetries;
  final Duration retryDelay;
  final Set<int> retryableStatuses;

  /// Injected by `DioRequestAdapter` so retries reuse the SAME configured dio
  /// (keeps auth/baseUrl/interceptors). Falls back to a bare `Dio()` only if the
  /// interceptor is used stand-alone.
  Dio? _dio;
  set dio(Dio d) => _dio = d;

  @override
  void onError(DioException err, ErrorInterceptorHandler handler) async {
    final requestOptions = err.requestOptions;
    final retryCount = requestOptions.extra['retry_count'] as int? ?? 0;
    final status = err.response?.statusCode;
    if (retryCount < maxRetries &&
        status != null &&
        retryableStatuses.contains(status)) {
      await Future<void>.delayed(retryDelay * (retryCount + 1));
      requestOptions.extra['retry_count'] = retryCount + 1;
      try {
        // FIX: reuse the SAME configured Dio (keeps auth/baseUrl/interceptors).
        // The old core did `Dio().fetch(...)` on a bare client, dropping all of
        // that — a retried 401-refresh or 503 went out unauthenticated / to a
        // relative URL.
        final response = await (_dio ?? Dio()).fetch<dynamic>(requestOptions);
        handler.resolve(response);
      } catch (_) {
        handler.next(err);
      }
    } else {
      handler.next(err);
    }
  }
}

class LoggingInterceptor extends Interceptor {
  LoggingInterceptor({void Function(String)? logger}) : logger = logger ?? _noop;

  final void Function(String message) logger;
  static void _noop(String message) {}

  @override
  void onRequest(RequestOptions options, RequestInterceptorHandler handler) {
    logger('${options.method} ${options.path}');
    handler.next(options);
  }

  @override
  void onResponse(Response<dynamic> response, ResponseInterceptorHandler handler) {
    logger('${response.statusCode} ${response.requestOptions.path}');
    handler.next(response);
  }

  @override
  void onError(DioException err, ErrorInterceptorHandler handler) {
    logger('ERROR ${err.message}');
    handler.next(err);
  }
}
''';

  String get _pagination => r'''// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by openapi_flutter_gen (--emit-target=runtime)
//

abstract class PaginatedResponse<T> {
  List<T> get items;
  Future<PaginatedResponse<T>?> getNextPage();
  bool hasNextPage();
}

class OffsetPaginatedResponse<T> extends PaginatedResponse<T> {
  OffsetPaginatedResponse({
    required this.items,
    required this.total,
    required this.offset,
    required this.limit,
    this.fetchNext,
  });

  @override
  final List<T> items;
  final int total;
  final int offset;
  final int limit;
  final Future<OffsetPaginatedResponse<T>?> Function(int nextOffset)? fetchNext;

  @override
  Future<OffsetPaginatedResponse<T>?> getNextPage() {
    final nextOffset = offset + limit;
    if (nextOffset >= total) return Future.value(null);
    if (fetchNext == null) return Future.value(null);
    return fetchNext!(nextOffset);
  }

  @override
  bool hasNextPage() => offset + limit < total;
}

class CursorPaginatedResponse<T, C> extends PaginatedResponse<T> {
  CursorPaginatedResponse({
    required this.items,
    this.nextCursor,
    this.fetchNext,
  });

  @override
  final List<T> items;
  final C? nextCursor;
  final Future<CursorPaginatedResponse<T, C>?> Function(C cursor)? fetchNext;

  @override
  Future<CursorPaginatedResponse<T, C>?> getNextPage() {
    if (nextCursor == null) return Future.value(null);
    if (fetchNext == null) return Future.value(null);
    return fetchNext!(nextCursor as C);
  }

  @override
  bool hasNextPage() => nextCursor != null;
}

extension PaginationExtension<T> on Future<PaginatedResponse<T>> {
  Future<void> forEach(Future<void> Function(T item) callback) async {
    PaginatedResponse<T>? current = await this;
    while (current != null) {
      for (final item in current.items) {
        await callback(item);
      }
      if (!current.hasNextPage()) break;
      current = await current.getNextPage();
    }
  }

  Future<List<T>> toList() async {
    final result = <T>[];
    await forEach((item) async => result.add(item));
    return result;
  }
}
''';
}
