// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by openapi_flutter_gen
//

/// Object model for `Address` from the SumUp API spec.
class Address {
  const Address({
    required this.street,
    required this.city,
    this.state,
    this.zip,
    required this.country,
  });

  final String street;
  final String city;
  final String? state;
  final String? zip;
  final String country;

  factory Address.fromJson(Map<String, dynamic> json) {
    return Address(
      street: json['street'] as String,
      city: json['city'] as String,
      state: json['state'] != null ? json['state'] as String : null,
      zip: json['zip'] != null ? json['zip'] as String : null,
      country: json['country'] as String,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'street': street,
      'city': city,
      if (state != null) 'state': state!,
      if (zip != null) 'zip': zip!,
      'country': country,
    };
  }

  Address copyWith({
    String? street,
    String? city,
    String? state,
    String? zip,
    String? country,
  }) {
    if (street == null &&
        city == null &&
        state == null &&
        zip == null &&
        country == null) return this;

    return Address(
      street: street ?? this.street,
      city: city ?? this.city,
      state: state ?? this.state,
      zip: zip ?? this.zip,
      country: country ?? this.country,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! Address) return false;
    return street == other.street &&
        city == other.city &&
        state == other.state &&
        zip == other.zip &&
        country == other.country;
  }

  @override
  int get hashCode => Object.hash(street, city, state, zip, country);

  @override
  String toString() =>
      'Address(street=$street, city=$city, state=$state, zip=$zip, country=$country)';
}
