// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by openapi_flutter_gen
//
import 'address.dart';
import 'userrole.dart';

/// Object model for `CreateUserRequest` from the SumUp API spec.
class CreateUserRequest {
  const CreateUserRequest({
    required this.email,
    required this.name,
    this.role,
    this.address,
  });

  final String email;
  final String name;
  final UserRole? role;
  final Address? address;

  factory CreateUserRequest.fromJson(Map<String, dynamic> json) {
    return CreateUserRequest(
      email: json['email'] as String,
      name: json['name'] as String,
      role: json['role'] != null
          ? UserRole.fromJson(json['role'] as String)
          : null,
      address: json['address'] != null
          ? Address.fromJson(json['address'] as Map<String, dynamic>)
          : null,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'email': email,
      'name': name,
      if (role != null) 'role': role!.toJson(),
      if (address != null) 'address': address!.toJson(),
    };
  }

  CreateUserRequest copyWith({
    String? email,
    String? name,
    UserRole? role,
    Address? address,
  }) {
    if (email == null && name == null && role == null && address == null)
      return this;

    return CreateUserRequest(
      email: email ?? this.email,
      name: name ?? this.name,
      role: role ?? this.role,
      address: address ?? this.address,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! CreateUserRequest) return false;
    return email == other.email &&
        name == other.name &&
        role == other.role &&
        address == other.address;
  }

  @override
  int get hashCode => Object.hash(email, name, role, address);

  @override
  String toString() =>
      'CreateUserRequest(email=$email, name=$name, role=$role, address=$address)';
}
