// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by openapi_flutter_gen
//

/// Object model for `CreateOrderRequest` from the SumUp API spec.
class CreateOrderRequest {
  const CreateOrderRequest({
    required this.petId,
    required this.userId,
    this.quantity,
  });

  final int petId;
  final String userId;
  final int? quantity;

  factory CreateOrderRequest.fromJson(Map<String, dynamic> json) {
    return CreateOrderRequest(
      petId: (json['pet_id'] as num).toInt(),
      userId: json['user_id'] as String,
      quantity:
          json['quantity'] != null ? (json['quantity'] as num).toInt() : null,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'pet_id': petId,
      'user_id': userId,
      if (quantity != null) 'quantity': quantity!,
    };
  }

  CreateOrderRequest copyWith({
    int? petId,
    String? userId,
    int? quantity,
  }) {
    if (petId == null && userId == null && quantity == null) return this;

    return CreateOrderRequest(
      petId: petId ?? this.petId,
      userId: userId ?? this.userId,
      quantity: quantity ?? this.quantity,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! CreateOrderRequest) return false;
    return petId == other.petId &&
        userId == other.userId &&
        quantity == other.quantity;
  }

  @override
  int get hashCode => Object.hash(petId, userId, quantity);

  @override
  String toString() =>
      'CreateOrderRequest(petId=$petId, userId=$userId, quantity=$quantity)';
}
