// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by openapi_flutter_gen
//
import 'petstatus.dart';

/// Object model for `CreatePetRequest` from the SumUp API spec.
class CreatePetRequest {
  const CreatePetRequest({
    required this.name,
    this.tag,
    this.status,
    this.categoryId,
    this.photoUrls,
  });

  final String name;
  final String? tag;
  final PetStatus? status;
  final int? categoryId;
  final List<String>? photoUrls;

  factory CreatePetRequest.fromJson(Map<String, dynamic> json) {
    return CreatePetRequest(
      name: json['name'] as String,
      tag: json['tag'] != null ? json['tag'] as String : null,
      status: json['status'] != null
          ? PetStatus.fromJson(json['status'] as String)
          : null,
      categoryId: json['category_id'] != null
          ? (json['category_id'] as num).toInt()
          : null,
      photoUrls: json['photo_urls'] != null
          ? json['photo_urls'] as List<String>
          : null,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'name': name,
      if (tag != null) 'tag': tag!,
      if (status != null) 'status': status!.toJson(),
      if (categoryId != null) 'category_id': categoryId!,
      if (photoUrls != null) 'photo_urls': photoUrls!,
    };
  }

  CreatePetRequest copyWith({
    String? name,
    String? tag,
    PetStatus? status,
    int? categoryId,
    List<String>? photoUrls,
  }) {
    if (name == null &&
        tag == null &&
        status == null &&
        categoryId == null &&
        photoUrls == null) return this;

    return CreatePetRequest(
      name: name ?? this.name,
      tag: tag ?? this.tag,
      status: status ?? this.status,
      categoryId: categoryId ?? this.categoryId,
      photoUrls: photoUrls ?? this.photoUrls,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! CreatePetRequest) return false;
    return name == other.name &&
        tag == other.tag &&
        status == other.status &&
        categoryId == other.categoryId &&
        photoUrls == other.photoUrls;
  }

  @override
  int get hashCode => Object.hash(name, tag, status, categoryId, photoUrls);

  @override
  String toString() =>
      'CreatePetRequest(name=$name, tag=$tag, status=$status, categoryId=$categoryId, photoUrls=$photoUrls)';
}
