// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by openapi_flutter_gen
//
import 'errordetail.dart';

/// Object model for `Error` from the SumUp API spec.
class Error {
  const Error({
    required this.code,
    required this.message,
    this.details,
  });

  final int code;
  final String message;
  final List<ErrorDetail>? details;

  factory Error.fromJson(Map<String, dynamic> json) {
    return Error(
      code: (json['code'] as num).toInt(),
      message: json['message'] as String,
      details: json['details'] != null
          ? List<ErrorDetail>.generate((json['details'] as List).length,
              (i) => ErrorDetail.fromJson((json['details'] as List)[i]),
              growable: false)
          : null,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'code': code,
      'message': message,
      if (details != null) 'details': details!.map((e) => e.toJson()).toList(),
    };
  }

  Error copyWith({
    int? code,
    String? message,
    List<ErrorDetail>? details,
  }) {
    if (code == null && message == null && details == null) return this;

    return Error(
      code: code ?? this.code,
      message: message ?? this.message,
      details: details ?? this.details,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! Error) return false;
    return code == other.code &&
        message == other.message &&
        details == other.details;
  }

  @override
  int get hashCode => Object.hash(code, message, details);

  @override
  String toString() => 'Error(code=$code, message=$message, details=$details)';
}
