// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by openapi_flutter_gen
//
import 'orderstatus.dart';

/// Object model for `Order` from the SumUp API spec.
class Order {
  const Order({
    required this.id,
    required this.petId,
    required this.userId,
    this.quantity,
    required this.status,
    this.shipDate,
    this.complete,
  });

  final String id;
  final int petId;
  final String userId;
  final int? quantity;
  final OrderStatus status;
  final DateTime? shipDate;
  final bool? complete;

  factory Order.fromJson(Map<String, dynamic> json) {
    return Order(
      id: json['id'] as String,
      petId: (json['pet_id'] as num).toInt(),
      userId: json['user_id'] as String,
      quantity:
          json['quantity'] != null ? (json['quantity'] as num).toInt() : null,
      status: OrderStatus.fromJson(json['status'] as String),
      shipDate: json['ship_date'] != null
          ? DateTime.parse(json['ship_date'] as String)
          : null,
      complete: json['complete'] != null ? json['complete'] as bool : null,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'pet_id': petId,
      'user_id': userId,
      if (quantity != null) 'quantity': quantity!,
      'status': status.toJson(),
      if (shipDate != null) 'ship_date': shipDate!.toIso8601String(),
      if (complete != null) 'complete': complete!,
    };
  }

  Order copyWith({
    String? id,
    int? petId,
    String? userId,
    int? quantity,
    OrderStatus? status,
    DateTime? shipDate,
    bool? complete,
  }) {
    if (id == null &&
        petId == null &&
        userId == null &&
        quantity == null &&
        status == null &&
        shipDate == null &&
        complete == null) return this;

    return Order(
      id: id ?? this.id,
      petId: petId ?? this.petId,
      userId: userId ?? this.userId,
      quantity: quantity ?? this.quantity,
      status: status ?? this.status,
      shipDate: shipDate ?? this.shipDate,
      complete: complete ?? this.complete,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! Order) return false;
    return id == other.id &&
        petId == other.petId &&
        userId == other.userId &&
        quantity == other.quantity &&
        status == other.status &&
        shipDate == other.shipDate &&
        complete == other.complete;
  }

  @override
  int get hashCode =>
      Object.hash(id, petId, userId, quantity, status, shipDate, complete);

  @override
  String toString() =>
      'Order(id=$id, petId=$petId, userId=$userId, quantity=$quantity, status=$status, shipDate=$shipDate, complete=$complete)';
}
