// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by openapi_flutter_gen
//
import 'category.dart';
import 'petstatus.dart';

/// Object model for `Pet` from the SumUp API spec.
class Pet {
  const Pet({
    required this.id,
    required this.name,
    this.tag,
    this.status,
    this.category,
    this.photoUrls,
    this.createdAt,
  });

  final int id;
  final String name;
  final String? tag;
  final PetStatus? status;
  final Category? category;
  final List<String>? photoUrls;
  final DateTime? createdAt;

  factory Pet.fromJson(Map<String, dynamic> json) {
    return Pet(
      id: (json['id'] as num).toInt(),
      name: json['name'] as String,
      tag: json['tag'] != null ? json['tag'] as String : null,
      status: json['status'] != null
          ? PetStatus.fromJson(json['status'] as String)
          : null,
      category: json['category'] != null
          ? Category.fromJson(json['category'] as Map<String, dynamic>)
          : null,
      photoUrls:
          json['photoUrls'] != null ? json['photoUrls'] as List<String> : null,
      createdAt: json['createdAt'] != null
          ? DateTime.parse(json['createdAt'] as String)
          : null,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      if (tag != null) 'tag': tag!,
      if (status != null) 'status': status!.toJson(),
      if (category != null) 'category': category!.toJson(),
      if (photoUrls != null) 'photoUrls': photoUrls!,
      if (createdAt != null) 'createdAt': createdAt!.toIso8601String(),
    };
  }

  Pet copyWith({
    int? id,
    String? name,
    String? tag,
    PetStatus? status,
    Category? category,
    List<String>? photoUrls,
    DateTime? createdAt,
  }) {
    if (id == null &&
        name == null &&
        tag == null &&
        status == null &&
        category == null &&
        photoUrls == null &&
        createdAt == null) return this;

    return Pet(
      id: id ?? this.id,
      name: name ?? this.name,
      tag: tag ?? this.tag,
      status: status ?? this.status,
      category: category ?? this.category,
      photoUrls: photoUrls ?? this.photoUrls,
      createdAt: createdAt ?? this.createdAt,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! Pet) return false;
    return id == other.id &&
        name == other.name &&
        tag == other.tag &&
        status == other.status &&
        category == other.category &&
        photoUrls == other.photoUrls &&
        createdAt == other.createdAt;
  }

  @override
  int get hashCode =>
      Object.hash(id, name, tag, status, category, photoUrls, createdAt);

  @override
  String toString() =>
      'Pet(id=$id, name=$name, tag=$tag, status=$status, category=$category, photoUrls=$photoUrls, createdAt=$createdAt)';
}
