// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by openapi_flutter_gen
//
// ignore_for_file: constant_identifier_names

/// Enum for `PetStatus` from the SumUp API spec.
enum PetStatus {
  available('available'),
  pending('pending'),
  sold('sold');

  const PetStatus(this.value);
  final String value;

  static PetStatus fromJson(String json) {
    return PetStatus.values.firstWhere(
      (e) => e.name == json || e.value == json,
      orElse: () => throw ArgumentError('Unknown PetStatus: $json'),
    );
  }

  String toJson() => value;
}
