// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by openapi_flutter_gen
//
// ignore_for_file: constant_identifier_names

/// Enum for `Status` from the SumUp API spec.
enum Status {
  available('available'),
  pending('pending'),
  sold('sold');

  const Status(this.value);
  final String value;

  static Status fromJson(String json) {
    return Status.values.firstWhere(
      (e) => e.name == json || e.value == json,
      orElse: () => throw ArgumentError('Unknown Status: $json'),
    );
  }

  String toJson() => value;
}
