// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by openapi_flutter_gen
//
// ignore_for_file: constant_identifier_names

/// Enum for `UserRole` from the SumUp API spec.
enum UserRole {
  admin('admin'),
  user('user'),
  moderator('moderator');

  const UserRole(this.value);
  final String value;

  static UserRole fromJson(String json) {
    return UserRole.values.firstWhere(
      (e) => e.name == json || e.value == json,
      orElse: () => throw ArgumentError('Unknown UserRole: $json'),
    );
  }

  String toJson() => value;
}
