// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by openapi_flutter_gen
//
import 'address.dart';
import 'userrole.dart';

/// Object model for `User` from the SumUp API spec.
class User {
  const User({
    required this.id,
    required this.email,
    this.name,
    this.role,
    this.address,
    this.createdAt,
  });

  final String id;
  final String email;
  final String? name;
  final UserRole? role;
  final Address? address;
  final DateTime? createdAt;

  factory User.fromJson(Map<String, dynamic> json) {
    return User(
      id: json['id'] as String,
      email: json['email'] as String,
      name: json['name'] != null ? json['name'] as String : null,
      role: json['role'] != null
          ? UserRole.fromJson(json['role'] as String)
          : null,
      address: json['address'] != null
          ? Address.fromJson(json['address'] as Map<String, dynamic>)
          : null,
      createdAt: json['created_at'] != null
          ? DateTime.parse(json['created_at'] as String)
          : null,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'email': email,
      if (name != null) 'name': name!,
      if (role != null) 'role': role!.toJson(),
      if (address != null) 'address': address!.toJson(),
      if (createdAt != null) 'created_at': createdAt!.toIso8601String(),
    };
  }

  User copyWith({
    String? id,
    String? email,
    String? name,
    UserRole? role,
    Address? address,
    DateTime? createdAt,
  }) {
    if (id == null &&
        email == null &&
        name == null &&
        role == null &&
        address == null &&
        createdAt == null) return this;

    return User(
      id: id ?? this.id,
      email: email ?? this.email,
      name: name ?? this.name,
      role: role ?? this.role,
      address: address ?? this.address,
      createdAt: createdAt ?? this.createdAt,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! User) return false;
    return id == other.id &&
        email == other.email &&
        name == other.name &&
        role == other.role &&
        address == other.address &&
        createdAt == other.createdAt;
  }

  @override
  int get hashCode => Object.hash(id, email, name, role, address, createdAt);

  @override
  String toString() =>
      'User(id=$id, email=$email, name=$name, role=$role, address=$address, createdAt=$createdAt)';
}
