// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by openapi_flutter_gen
//
import 'package:dio/dio.dart';

class BearerAuthSecurity {
  BearerAuthSecurity(
      {this.token,
      this.tokenProvider,
      this.headerName = 'Authorization',
      this.tokenPrefix = 'Bearer '});

  final String? token;
  final Future<String> Function()? tokenProvider;
  final String headerName;
  final String tokenPrefix;

  Interceptor createInterceptor() => _BearerAuthSecurityInterceptor(this);
}

class _BearerAuthSecurityInterceptor extends Interceptor {
  _BearerAuthSecurityInterceptor(this.security);
  final BearerAuthSecurity security;

  @override
  void onRequest(
      RequestOptions options, RequestInterceptorHandler handler) async {
    var token = security.token;
    token ??= await security.tokenProvider?.call();
    if (token != null) {
      options.headers[security.headerName] = '${security.tokenPrefix}$token';
    }
    handler.next(options);
  }
}
