String _toPascalCase(String s) {
  if (s.isEmpty) return s;
  return s
      .replaceAll(RegExp(r'[\[\]]+'), '_')
      .split(RegExp(r'[\._\-\s]+'))
      .where((p) => p.isNotEmpty)
      .map((p) => p[0].toUpperCase() + p.substring(1))
      .join();
}

String _toCamelCase(String s) {
  if (s.isEmpty) return s;
  final pascal = _toPascalCase(s);
  return pascal[0].toLowerCase() + pascal.substring(1);
}

String sanitizeFieldName(String name) {
  final cleaned = _toCamelCase(
    name
        .replaceAll(RegExp(r'[\[\]()]+'), '_')
        .replaceAll(RegExp(r'[\.]+'), '_'),
  );
  return safeDartName(cleaned.isNotEmpty ? cleaned : 'value');
}

String safeDartName(String name) {
  const keywords = {
    'abstract',
    'as',
    'assert',
    'async',
    'await',
    'break',
    'case',
    'catch',
    'class',
    'const',
    'continue',
    'covariant',
    'default',
    'deferred',
    'do',
    'dynamic',
    'else',
    'enum',
    'export',
    'extends',
    'extension',
    'external',
    'factory',
    'false',
    'final',
    'finally',
    'for',
    'function',
    'get',
    'hide',
    'if',
    'implements',
    'import',
    'in',
    'interface',
    'is',
    'library',
    'mixin',
    'new',
    'null',
    'on',
    'operator',
    'part',
    'record',
    'rethrow',
    'return',
    'sealed',
    'set',
    'show',
    'static',
    'super',
    'switch',
    'sync',
    'this',
    'throw',
    'true',
    'try',
    'type',
    'typedef',
    'var',
    'void',
    'when',
    'while',
    'with',
    'yield',
    'wait',
    'value',
    'error',
  };
  if (keywords.contains(name)) return '${name}_';
  return name;
}

String sanitizeClassName(String name) => safeDartName(_toPascalCase(name));

String indent(String code, {int level = 1}) {
  final indent = '  ' * level;
  return code.splitMapJoin('\n', onNonMatch: (line) {
    if (line.trim().isEmpty) return line;
    return '$indent$line';
  });
}

String generateFileHeader() {
  return '''
// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by openapi_flutter_gen
//
''';
}

String generatePubspecContent(String packageName, String description) {
  final safe = description
      .replaceAll(RegExp(r'[\r\n]+'), ' ')
      .replaceAll("'", "''")
      .trim();
  final safeDesc = safe.length > 120 ? '${safe.substring(0, 117)}...' : safe;
  return '''
name: $packageName
description: '$safeDesc'
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.12.0

dependencies:
  dio: ^5.11.1
  collection: ^1.19.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
''';
}

/// pubspec for a pure-surface (Kiota-lite) client: the transport runtime is
/// provided by the shared `purple_openapi_core` package (git-dep, ref master),
/// which replaces the direct `dio:`/`collection:` deps.
///
/// [usesDio] adds a direct `dio` dep when the client's binary/multipart
/// operations import dio's `FormData`/`MultipartFile` (pure JSON clients don't
/// touch dio directly — they only build a transport-neutral RequestInformation).
String generatePureSurfacePubspecContent(
    String packageName, String description, String corePackage,
    {bool usesDio = false}) {
  final safe = description
      .replaceAll(RegExp(r'[\r\n]+'), ' ')
      .replaceAll("'", "''")
      .trim();
  final safeDesc = safe.length > 120 ? '${safe.substring(0, 117)}...' : safe;
  final dioDep = usesDio
      ? '  # Binary/multipart operations reference dio FormData/MultipartFile directly.\n'
          '  dio: ^5.11.1\n'
      : '';
  return '''
name: $packageName
description: '$safeDesc'
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.12.0

dependencies:
  $corePackage:
    git:
      url: https://xamapps.visualstudio.com/PurpleFoundation/_git/purple_foundation
      ref: master
      path: packages/purple_openapi_core
$dioDep
dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
''';
}
