String _toPascalCase(String s) {
  if (s.isEmpty) return s;
  return s
      .replaceAll(RegExp(r'[\[\]]+'), '_')
      // Drop the `$` OData sigil (Azure uses $top/$skip/$expand/$filter…). It is
      // not a valid Dart identifier char and must never leak into a class/field
      // name, while the ORIGINAL param name (with `$`) is still used as the wire
      // key by the api generator.
      .replaceAll(r'$', '')
      .split(RegExp(r'[\._\-\s]+'))
      .where((p) => p.isNotEmpty)
      .map((p) => p[0].toUpperCase() + p.substring(1))
      .join();
}

String _toCamelCase(String s) {
  if (s.isEmpty) return s;
  final pascal = _toPascalCase(s);
  return pascal[0].toLowerCase() + pascal.substring(1);
}

String sanitizeFieldName(String name) {
  final cleaned = _toCamelCase(
    name
        .replaceAll(RegExp(r'[\[\]()]+'), '_')
        .replaceAll(RegExp(r'[\.]+'), '_'),
  );
  return safeDartName(cleaned.isNotEmpty ? cleaned : 'value');
}

String safeDartName(String name) {
  const keywords = {
    'abstract',
    'as',
    'assert',
    'async',
    'await',
    'break',
    'case',
    'catch',
    'class',
    'const',
    'continue',
    'covariant',
    'default',
    'deferred',
    'do',
    'dynamic',
    'else',
    'enum',
    'export',
    'extends',
    'extension',
    'external',
    'factory',
    'false',
    'final',
    'finally',
    'for',
    'function',
    'get',
    'hide',
    'if',
    'implements',
    'import',
    'in',
    'interface',
    'is',
    'library',
    'mixin',
    'new',
    'null',
    'on',
    'operator',
    'part',
    'record',
    'rethrow',
    'return',
    'sealed',
    'set',
    'show',
    'static',
    'super',
    'switch',
    'sync',
    'this',
    'throw',
    'true',
    'try',
    'type',
    'typedef',
    'var',
    'void',
    'when',
    'while',
    'with',
    'yield',
    'wait',
    'value',
    'error',
  };
  if (keywords.contains(name)) return '${name}_';
  return name;
}

String sanitizeClassName(String name) => safeDartName(_toPascalCase(name));

/// Escapes a raw wire string (JSON key, query-param name, URL path) for safe
/// embedding inside a single-quoted Dart string literal. Azure DevOps uses
/// OData `$`-prefixed keys (`$expand`, `$top`) and `$`-containing path segments
/// (`.../workitems/${type}`); an unescaped `$` triggers Dart interpolation and
/// either references an undefined member or is a syntax error. Backslash and the
/// single quote are escaped too so arbitrary keys round-trip literally.
String escapeDartString(String raw) => raw
    .replaceAll(r'\', r'\\')
    .replaceAll(r'$', r'\$')
    .replaceAll("'", r"\'");

String indent(String code, {int level = 1}) {
  final indent = '  ' * level;
  return code.splitMapJoin('\n', onNonMatch: (line) {
    if (line.trim().isEmpty) return line;
    return '$indent$line';
  });
}

String generateFileHeader() {
  return '''
// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by openapi_flutter_gen
//
''';
}

String generatePubspecContent(String packageName, String description,
    {bool workspace = false}) {
  final safe = description
      .replaceAll(RegExp(r'[\r\n]+'), ' ')
      .replaceAll("'", "''")
      .trim();
  final safeDesc = safe.length > 180 ? '${safe.substring(0, 177)}...' : safe;
  // `resolution: workspace` requires a pub-workspace root in a parent dir; a
  // standalone generated package has none, so `dart pub get` fails outright.
  // Emit it only when the caller opts into monorepo/workspace layout.
  final resolutionLine = workspace ? '\nresolution: workspace' : '';
  return '''
name: $packageName
description: '$safeDesc'
version: 0.1.0
publish_to: none$resolutionLine

environment:
  sdk: ^3.12.0

dependencies:
  dio: ^5.11.1
  collection: ^1.19.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
''';
}

/// pubspec for a pure-surface (Kiota-lite) client: the transport runtime is
/// provided by the shared `purple_openapi_core` package (git-dep, ref master),
/// which replaces the direct `dio:`/`collection:` deps.
///
/// [usesDio] adds a direct `dio` dep when the client's binary/multipart
/// operations import dio's `FormData`/`MultipartFile` (pure JSON clients don't
/// touch dio directly — they only build a transport-neutral RequestInformation).
String generatePureSurfacePubspecContent(
    String packageName, String description, String corePackage,
    {bool usesDio = false, bool workspace = false}) {
  final safe = description
      .replaceAll(RegExp(r'[\r\n]+'), ' ')
      .replaceAll("'", "''")
      .trim();
  final safeDesc = safe.length > 180 ? '${safe.substring(0, 177)}...' : safe;
  final dioDep = usesDio
      ? '  # Binary/multipart operations reference dio FormData/MultipartFile directly.\n'
          '  dio: ^5.11.1\n'
      : '';
  // See generatePubspecContent: workspace resolution is opt-in only.
  final resolutionLine = workspace ? '\nresolution: workspace' : '';
  return '''
name: $packageName
description: '$safeDesc'
version: 0.1.0
publish_to: none$resolutionLine

environment:
  sdk: ^3.12.0

dependencies:
  $corePackage:
    git:
      url: https://xamapps.visualstudio.com/PurpleFoundation/_git/purple_foundation
      ref: master
      path: packages/purple_openapi_core
$dioDep
dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
''';
}
