
String _toSnakeCase(String s) {
  if (s.isEmpty) return s;
  return s
      .replaceAllMapped(RegExp(r'([A-Z]+)'), (m) => '_${m.group(1)!.toLowerCase()}')
      .replaceAll(RegExp(r'^_'), '')
      .replaceAll(RegExp(r'__+'), '_');
}

String _toPascalCase(String s) {
  if (s.isEmpty) return s;
  return s
      .split(RegExp(r'[\._\-\s]+'))
      .where((p) => p.isNotEmpty)
      .map((p) => p[0].toUpperCase() + p.substring(1))
      .join();
}

String _toCamelCase(String s) {
  if (s.isEmpty) return s;
  final pascal = _toPascalCase(s);
  return pascal[0].toLowerCase() + pascal.substring(1);
}

String modelFileName(String modelName) => '${_toSnakeCase(modelName)}.dart';

String serviceFileName(String tag) => '${_toSnakeCase(tag)}.dart';

String interfaceFileName(String name) => '${_toSnakeCase(name)}.dart';

String safeDartName(String name) {
  const keywords = {
    'abstract', 'as', 'assert', 'async', 'await', 'break', 'case', 'catch',
    'class', 'const', 'continue', 'covariant', 'default', 'deferred', 'do',
    'dynamic', 'else', 'enum', 'export', 'extends', 'extension', 'external',
    'factory', 'false', 'final', 'finally', 'for', 'function', 'get', 'hide',
    'if', 'implements', 'import', 'in', 'interface', 'is', 'library', 'mixin',
    'new', 'null', 'on', 'operator', 'part', 'record', 'rethrow', 'return',
    'sealed', 'set', 'show', 'static', 'super', 'switch', 'sync', 'this',
    'throw', 'true', 'try', 'type', 'typedef', 'var', 'void', 'when', 'while',
    'with', 'yield', 'wait', 'value', 'error',
  };
  if (keywords.contains(name)) return '${name}_';
  return name;
}

String sanitizeFieldName(String name) => safeDartName(_toCamelCase(name));

String sanitizeClassName(String name) => safeDartName(_toPascalCase(name));

String indent(String code, {int level = 1}) {
  final indent = '  ' * level;
  return code.splitMapJoin('\n', onNonMatch: (line) {
    if (line.trim().isEmpty) return line;
    return '$indent$line';
  });
}

String generateFileHeader() {
  return '''
// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by openapi_flutter_gen
//
''';
}

String generatePubspecContent(String packageName, String description) {
  final safe = description
      .replaceAll(RegExp(r'[\r\n]+'), ' ')
      .replaceAll("'", "''")
      .trim();
  final safeDesc = safe.length > 120 ? '${safe.substring(0, 117)}...' : safe;
  return '''
name: $packageName
description: '$safeDesc'
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  dio: any
  collection: any

dev_dependencies:
  lints: any
  test: any
''';
}
