// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by openapi_flutter_gen
//
import 'package:dio/dio.dart';

import '../models/createpetrequest.dart';
import '../models/status.dart';
import '../models/updatepetrequest.dart';
import 'createpet_result.dart';
import 'deletepet_result.dart';
import 'getpet_result.dart';
import 'listpets_result.dart';
import 'updatepet_result.dart';

class PetsApi {
  const PetsApi({required this.dio, this.baseUrl});

  final Dio dio;
  final String? baseUrl;

  Future<ListPetsResult> listPets({
    int? limit,
    Status? status,
    CancelToken? cancelToken,
    Map<String, dynamic>? extra,
    Options? options,
  }) async {
    final reqQueryParams = <String, dynamic>{};
    if (limit != null) reqQueryParams['limit'] = limit.toString();
    if (status != null) reqQueryParams['status'] = status.toJson().toString();

    final response = await dio.request<Map<String, dynamic>>(
      '/pets',
      queryParameters: reqQueryParams.isNotEmpty ? reqQueryParams : null,
      options: options ??
          Options(
            method: 'get',
            headers: null,
            extra: extra,
          ),
      cancelToken: cancelToken,
    );

    return ListPetsResult.fromResponse(response);
  }

  Future<CreatePetResult> createPet({
    required CreatePetRequest createPetRequest,
    CancelToken? cancelToken,
    Map<String, dynamic>? extra,
    Options? options,
  }) async {
    final response = await dio.request<Map<String, dynamic>>(
      '/pets',
      data: createPetRequest.toJson(),
      queryParameters: null,
      options: options ??
          Options(
            method: 'post',
            headers: null,
            extra: extra,
          ),
      cancelToken: cancelToken,
    );

    return CreatePetResult.fromResponse(response);
  }

  Future<GetPetResult> getPet({
    required int petId,
    CancelToken? cancelToken,
    Map<String, dynamic>? extra,
    Options? options,
  }) async {
    final response = await dio.request<Map<String, dynamic>>(
      '/pets/$petId',
      queryParameters: null,
      options: options ??
          Options(
            method: 'get',
            headers: null,
            extra: extra,
          ),
      cancelToken: cancelToken,
    );

    return GetPetResult.fromResponse(response);
  }

  Future<DeletePetResult> deletePet({
    required int petId,
    CancelToken? cancelToken,
    Map<String, dynamic>? extra,
    Options? options,
  }) async {
    final response = await dio.request<Map<String, dynamic>>(
      '/pets/$petId',
      queryParameters: null,
      options: options ??
          Options(
            method: 'delete',
            headers: null,
            extra: extra,
          ),
      cancelToken: cancelToken,
    );

    return DeletePetResult.fromResponse(response);
  }

  Future<UpdatePetResult> updatePet({
    required int petId,
    required UpdatePetRequest updatePetRequest,
    CancelToken? cancelToken,
    Map<String, dynamic>? extra,
    Options? options,
  }) async {
    final response = await dio.request<Map<String, dynamic>>(
      '/pets/$petId',
      data: updatePetRequest.toJson(),
      queryParameters: null,
      options: options ??
          Options(
            method: 'patch',
            headers: null,
            extra: extra,
          ),
      cancelToken: cancelToken,
    );

    return UpdatePetResult.fromResponse(response);
  }
}
