// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by openapi_flutter_gen
//
import 'package:dio/dio.dart';

import '../models/createuserrequest.dart';
import 'createuser_result.dart';
import 'getuser_result.dart';

class UsersApi {
  const UsersApi({required this.dio, this.baseUrl});

  final Dio dio;
  final String? baseUrl;

  Future<CreateUserResult> createUser({
    required CreateUserRequest createUserRequest,
    CancelToken? cancelToken,
    Map<String, dynamic>? extra,
    Options? options,
  }) async {
    final response = await dio.request<Map<String, dynamic>>(
      '/users',
      data: createUserRequest.toJson(),
      queryParameters: null,
      options: options ??
          Options(
            method: 'post',
            headers: null,
            extra: extra,
          ),
      cancelToken: cancelToken,
    );

    return CreateUserResult.fromResponse(response);
  }

  Future<GetUserResult> getUser({
    required String userId,
    CancelToken? cancelToken,
    Map<String, dynamic>? extra,
    Options? options,
  }) async {
    final response = await dio.request<Map<String, dynamic>>(
      '/users/$userId',
      queryParameters: null,
      options: options ??
          Options(
            method: 'get',
            headers: null,
            extra: extra,
          ),
      cancelToken: cancelToken,
    );

    return GetUserResult.fromResponse(response);
  }
}
