// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by openapi_flutter_gen
//
import 'package:dio/dio.dart';
import '../core/auth.dart';
import '../core/error_handler.dart';

import 'pets_api.dart';
import 'users_api.dart';
import 'orders_api.dart';

class ApiClient {
  ApiClient({
    this.baseUrl = 'https://petstore.example.com/api/v1',
    this.bearerAuth,
    this.errorHandler,
    Dio? dio,
    this.interceptors,
  }) : _dio = dio ?? Dio() {
    _dio.options.baseUrl = baseUrl;
    if (errorHandler != null) _addInterceptor(errorHandler!);
    final bearerAuthCopy = bearerAuth;
    if (bearerAuthCopy != null)
      _addInterceptor(bearerAuthCopy.createInterceptor());
    if (interceptors != null) _addInterceptors(interceptors!);
  }

  final String baseUrl;
  final BearerAuthSecurity? bearerAuth;
  final ApiErrorInterceptor? errorHandler;
  final List<Interceptor>? interceptors;
  final Dio _dio;
  bool _initialized = false;

  void _addInterceptor(Interceptor interceptor) =>
      _dio.interceptors.add(interceptor);
  void _addInterceptors(List<Interceptor> interceptors) =>
      _dio.interceptors.addAll(interceptors);

  Dio get dio {
    if (!_initialized) {
      _initialized = true;
      if (errorHandler != null) _addInterceptor(errorHandler!);
      final bearerAuthCopy = bearerAuth;
      if (bearerAuthCopy != null)
        _addInterceptor(bearerAuthCopy.createInterceptor());
      if (interceptors != null) _addInterceptors(interceptors!);
    }
    return _dio;
  }

  PetsApi get pets => PetsApi(dio: dio, baseUrl: baseUrl);
  UsersApi get users => UsersApi(dio: dio, baseUrl: baseUrl);
  OrdersApi get orders => OrdersApi(dio: dio, baseUrl: baseUrl);
}
