// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by openapi_flutter_gen
//
import 'package:dio/dio.dart';
import 'dart:isolate';

import '../models/createorderrequest.dart';
import '../models/status.dart';
import 'listorders_result.dart';
import 'placeorder_result.dart';

class OrdersApi {
  const OrdersApi({required this.dio, this.baseUrl});

  final Dio dio;
  final String? baseUrl;

  Future<ListOrdersResult> listOrders({
    String? userId,
    Status? status,
    CancelToken? cancelToken,
    Map<String, dynamic>? extra,
    Options? options,
  }) async {
    final reqQueryParams = <String, dynamic>{};
    if (userId != null) reqQueryParams['userId'] = userId.toString();
    if (status != null) reqQueryParams['status'] = status.toJson().toString();

    final response = await dio.request<Map<String, dynamic>>(
      '/orders',
      queryParameters: reqQueryParams.isNotEmpty ? reqQueryParams : null,
      options: options ??
          Options(
            method: 'get',
            headers: null,
            extra: extra,
          ),
      cancelToken: cancelToken,
    );

    final statusCode = response.statusCode ?? 0;
    final data = response.data;
    return Isolate.run(
        () => deserializeListOrders((statusCode: statusCode, data: data)));
  }

  Future<PlaceOrderResult> placeOrder({
    required CreateOrderRequest createOrderRequest,
    CancelToken? cancelToken,
    Map<String, dynamic>? extra,
    Options? options,
  }) async {
    final response = await dio.request<Map<String, dynamic>>(
      '/orders',
      data: createOrderRequest.toJson(),
      queryParameters: null,
      options: options ??
          Options(
            method: 'post',
            headers: null,
            extra: extra,
          ),
      cancelToken: cancelToken,
    );

    final statusCode = response.statusCode ?? 0;
    final data = response.data;
    return Isolate.run(
        () => deserializePlaceOrder((statusCode: statusCode, data: data)));
  }
}
