// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by openapi_flutter_gen
//

/// Object model for `Category` from the SumUp API spec.
class Category {
  const Category({
    required this.id,
    required this.name,
    this.subcategory,
  });

  final int id;
  final String name;
  final Category? subcategory;

  factory Category.fromJson(Map<String, dynamic> json) {
    return Category(
      id: (json['id'] as num).toInt(),
      name: json['name'] as String,
      subcategory: json['subcategory'] != null
          ? Category.fromJson(json['subcategory'] as Map<String, dynamic>)
          : null,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      if (subcategory != null) 'subcategory': subcategory!.toJson(),
    };
  }

  Category copyWith({
    int? id,
    String? name,
    Category? subcategory,
  }) {
    if (id == null && name == null && subcategory == null) return this;

    return Category(
      id: id ?? this.id,
      name: name ?? this.name,
      subcategory: subcategory ?? this.subcategory,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! Category) return false;
    return id == other.id &&
        name == other.name &&
        subcategory == other.subcategory;
  }

  @override
  int get hashCode => Object.hash(id, name, subcategory);

  @override
  String toString() => 'Category(id=$id, name=$name, subcategory=$subcategory)';
}
