// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by openapi_flutter_gen
//

/// Object model for `ErrorDetail` from the SumUp API spec.
class ErrorDetail {
  const ErrorDetail({
    required this.field,
    required this.message,
  });

  final String field;
  final String message;

  factory ErrorDetail.fromJson(Map<String, dynamic> json) {
    return ErrorDetail(
      field: json['field'] as String,
      message: json['message'] as String,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'field': field,
      'message': message,
    };
  }

  ErrorDetail copyWith({
    String? field,
    String? message,
  }) {
    if (field == null && message == null) return this;

    return ErrorDetail(
      field: field ?? this.field,
      message: message ?? this.message,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! ErrorDetail) return false;
    return field == other.field && message == other.message;
  }

  @override
  int get hashCode => Object.hash(field, message);

  @override
  String toString() => 'ErrorDetail(field=$field, message=$message)';
}
