// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by openapi_flutter_gen
//
// ignore_for_file: constant_identifier_names

/// Enum for `OrderStatus` from the SumUp API spec.
enum OrderStatus {
  pending('pending'),
  processing('processing'),
  shipped('shipped'),
  delivered('delivered'),
  cancelled('cancelled');

  const OrderStatus(this.value);
  final String value;

  static OrderStatus fromJson(String json) {
    return OrderStatus.values.firstWhere(
      (e) => e.name == json || e.value == json,
      orElse: () => throw ArgumentError('Unknown OrderStatus: $json'),
    );
  }

  String toJson() => value;
}
