// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by openapi_flutter_gen
//
import 'petstatus.dart';

/// Object model for `UpdatePetRequest` from the SumUp API spec.
class UpdatePetRequest {
  const UpdatePetRequest({
    this.name,
    this.tag,
    this.status,
    this.categoryId,
  });

  final String? name;
  final String? tag;
  final PetStatus? status;
  final int? categoryId;

  factory UpdatePetRequest.fromJson(Map<String, dynamic> json) {
    return UpdatePetRequest(
      name: json['name'] != null ? json['name'] as String : null,
      tag: json['tag'] != null ? json['tag'] as String : null,
      status: json['status'] != null
          ? PetStatus.fromJson(json['status'] as String)
          : null,
      categoryId: json['category_id'] != null
          ? (json['category_id'] as num).toInt()
          : null,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      if (name != null) 'name': name!,
      if (tag != null) 'tag': tag!,
      if (status != null) 'status': status!.toJson(),
      if (categoryId != null) 'category_id': categoryId!,
    };
  }

  UpdatePetRequest copyWith({
    String? name,
    String? tag,
    PetStatus? status,
    int? categoryId,
  }) {
    if (name == null && tag == null && status == null && categoryId == null)
      return this;

    return UpdatePetRequest(
      name: name ?? this.name,
      tag: tag ?? this.tag,
      status: status ?? this.status,
      categoryId: categoryId ?? this.categoryId,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! UpdatePetRequest) return false;
    return name == other.name &&
        tag == other.tag &&
        status == other.status &&
        categoryId == other.categoryId;
  }

  @override
  int get hashCode => Object.hash(name, tag, status, categoryId);

  @override
  String toString() =>
      'UpdatePetRequest(name=$name, tag=$tag, status=$status, categoryId=$categoryId)';
}
